# Part 1: Data Assessment

## Objective

Examine the provided arXiv research papers, identify the available file types and metadata,
assess the quality of the data, and determine what information is usable for the RAG pipeline.

In [4]:
from pathlib import Path
import pandas as pd
from pypdf import PdfReader

cwd = Path.cwd()

if (cwd / "data").exists():
    data_dir = cwd / "data"
else:
    data_dir = cwd.parent / "data"

print("Data directory:", data_dir)

Data directory: /Users/janhhavibeley/Desktop/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data

In [5]:
files = sorted([
    file for file in data_dir.iterdir()
    if file.is_file() and file.name != ".gitkeep"
])

print("number of data files:", len(files))

for file in files:
    print(file.name)

number of data files: 5
2608.20316v1_Pandora's AI Model Routing Box Efficient Allocation with Costly Value Estimation.pdf
2608.20318v1_AI4AI-Bench Benchmarking LLM Agents in Algorithmic Design for Recursive Self-Imp.pdf
2608.20319v1_Inducing Task Models from Computer-Use Traces.pdf
2608.20320v1_An Agentic Approach for Active Data Collection, Travel Behavior Modeling, and We.pdf
2608.20331v1_G-CARL Grounded Checklist-Aligned Reward Learning for Patient-Oriented Medical R.pdf

In [6]:
file_info = []

for file in files:
    file_info.append({
        "filename": file.name,
        "file_type": file.suffix.lower(),
        "size_mb": round(file.stat().st_size / (1024 * 1024), 2)
    })

file_df = pd.DataFrame(file_info)
file_df

                                            filename file_type  size_mb
0  2608.20316v1_Pandora's AI Model Routing Box Ef...      .pdf     0.59
1  2608.20318v1_AI4AI-Bench Benchmarking LLM Agen...      .pdf     1.48
2  2608.20319v1_Inducing Task Models from Compute...      .pdf     4.67
3  2608.20320v1_An Agentic Approach for Active Da...      .pdf     2.58
4  2608.20331v1_G-CARL Grounded Checklist-Aligned...      .pdf     3.63

In [7]:
paper_info = []

for file in files:
    if file.suffix.lower() == ".pdf":
        try:
            reader = PdfReader(file)
            metadata = reader.metadata

            pages_with_text = 0
            total_characters = 0

            for page in reader.pages:
                text = page.extract_text()

                if text and text.strip():
                    pages_with_text += 1
                    total_characters += len(text)

            paper_info.append({
                "filename": file.name,
                "title": metadata.get("/Title") if metadata else None,
                "author": metadata.get("/Author") if metadata else None,
                "num_pages": len(reader.pages),
                "pages_with_text": pages_with_text,
                "text_characters": total_characters,
                "readable": total_characters > 0
            })

        except Exception as e:
            paper_info.append({
                "filename": file.name,
                "title": None,
                "author": None,
                "num_pages": None,
                "pages_with_text": 0,
                "text_characters": 0,
                "readable": False
            })

papers_df = pd.DataFrame(paper_info)
papers_df

,filename,title,author,num_pages,pages_with_text,text_characters,readable
0,2608.20316v1_Pandora's AI Model Routing Box Ef...,Pandora's AI Model Routing Box: Efficient Allo...,Adam Fisch; Shubhendu Trivedi; Fantine Huot; W...,28,28,89597,True
1,2608.20318v1_AI4AI-Bench Benchmarking LLM Agen...,AI4AI-Bench: Benchmarking LLM Agents in Algori...,Yizhe Chi; Wenyi Li; Deyao Hong; Xiaoqiu Wang;...,19,19,76707,True
2,2608.20319v1_Inducing Task Models from Compute...,Inducing Task Models from Computer-Use Traces,Yucheng Jiang; Zora Zhiruo Wang; Ruishi Chen; ...,23,23,85873,True
3,2608.20320v1_An Agentic Approach for Active Da...,An Agentic Approach for Active Data Collection...,Narges Ahmadi; Yubo Jiao; Jônatas Augusto Manz...,25,25,73593,True
4,2608.20331v1_G-CARL Grounded Checklist-Aligned...,G-CARL: Grounded Checklist-Aligned Reward Lear...,Shiao Xie; Siyu Chen; Jianwei Lv; Bo Yuan; Yuj...,9,9,48596,True

In [8]:
papers_df.isnull().sum()

filename           0
title              0
author             0
num_pages          0
pages_with_text    0
text_characters    0
readable           0
dtype: int64

In [9]:
papers_df[[
    "filename",
    "title",
    "author",
    "num_pages",
    "pages_with_text",
    "text_characters",
    "readable"
]]

,filename,title,author,num_pages,pages_with_text,text_characters,readable
0,2608.20316v1_Pandora's AI Model Routing Box Ef...,Pandora's AI Model Routing Box: Efficient Allo...,Adam Fisch; Shubhendu Trivedi; Fantine Huot; W...,28,28,89597,True
1,2608.20318v1_AI4AI-Bench Benchmarking LLM Agen...,AI4AI-Bench: Benchmarking LLM Agents in Algori...,Yizhe Chi; Wenyi Li; Deyao Hong; Xiaoqiu Wang;...,19,19,76707,True
2,2608.20319v1_Inducing Task Models from Compute...,Inducing Task Models from Computer-Use Traces,Yucheng Jiang; Zora Zhiruo Wang; Ruishi Chen; ...,23,23,85873,True
3,2608.20320v1_An Agentic Approach for Active Da...,An Agentic Approach for Active Data Collection...,Narges Ahmadi; Yubo Jiao; Jônatas Augusto Manz...,25,25,73593,True
4,2608.20331v1_G-CARL Grounded Checklist-Aligned...,G-CARL: Grounded Checklist-Aligned Reward Lear...,Shiao Xie; Siyu Chen; Jianwei Lv; Bo Yuan; Yuj...,9,9,48596,True

In [10]:
for file in files:
    reader = PdfReader(file)
    metadata = reader.metadata

    print("\nFILE:", file.name)

    if metadata:
        print("Metadata fields:", list(metadata.keys()))
    else:
        print("No metadata found")

FILE: 2608.20316v1_Pandora's AI Model Routing Box Efficient Allocation with Costly Value Estimation.pdf
Metadata fields: ['/Author', '/Creator', '/DOI', '/License', '/PTEX.Fullbanner', '/Producer', '/Title', '/Trapped', '/arXivID']

FILE: 2608.20318v1_AI4AI-Bench Benchmarking LLM Agents in Algorithmic Design for Recursive Self-Imp.pdf
Metadata fields: ['/Author', '/Creator', '/DOI', '/License', '/PTEX.Fullbanner', '/Producer', '/Title', '/Trapped', '/arXivID']

FILE: 2608.20319v1_Inducing Task Models from Computer-Use Traces.pdf
Metadata fields: ['/Author', '/Creator', '/DOI', '/License', '/PTEX.Fullbanner', '/Producer', '/Title', '/Trapped', '/arXivID']

FILE: 2608.20320v1_An Agentic Approach for Active Data Collection, Travel Behavior Modeling, and We.pdf
Metadata fields: ['/Author', '/Creator', '/DOI', '/License', '/PTEX.Fullbanner', '/Producer', '/Title', '/Trapped', '/arXivID']

FILE: 2608.20331v1_G-CARL Grounded Checklist-Aligned Reward Learning for Patient-Oriented Medical R.pdf
Metadata fields: ['/Author', '/Creator', '/DOI', '/License', '/PTEX.Fullbanner', '/Producer', '/TemplateVersion', '/Title', '/Trapped', '/arXivID']

In [11]:
reader = PdfReader(files[0])
sample_text = reader.pages[0].extract_text()

print(sample_text[:2000])

2026-08-21
Pandora’s AI Model Routing Box: Efficient
Allocation with Costly Value Estimation
Adam Fisch∗, Shubhendu Trivedi, Fantine Huot, William W. Cohen, Michael Kaisers, Mirella Lapata, Kate
Larson, Jacob Eisenstein∗
Google DeepMind
Heterogeneous AI systems composed of multiple models, architectures, harnesses, or inference-time
settings can improve quality and efficiency by routing queries to thespecialistwho can answer most
effectively at the lowest cost. Routing requires estimating each specialist’s expected return, but this value
estimation has a cost. Cheap estimators (e.g., embedding-based predictors) are fast but noisy, while ac-
curate estimators (e.g., fine-tuned models with access to retrieval results or partial reasoning traces) are
expensive. We formalize this tradeoff as an instance of Pandora’s Box, the classical problem of optimal
search with costly inspection. Under a Gaussian signal model, the resulting policies have closed-form
value-of-information expressions that determine, for each specialist and input, whether refining the
value estimate is worth its cost. We call the centralized policy Pandora’s Router. We extend this to a
decentralized setting, Pandora’s Bidder, where specialists independently decide whether to invest in
self-assessment before accepting an offered price to claim a query. Experiments across three domains—a
standard multi-LLM benchmark, retrieval-augmented specialists, and LLMs with variable inference-time
reasoning—show that Pandora’s Router matches the routing quality of exhaustive estimation, while
querying the expensive estimator far less often. In the decentralized setting, value-of-information
reasoning improves allocative efficiency when competing estimates are accurate; when competing
estimates are noisy, however, it can increase the strategic specialist’s utility at the expense of others.
1. Introduction
AI model providers now often offer heterogeneous model families spanning a wide range of costs and
capabilities:

In [12]:
for file in files:
    reader = PdfReader(file)
    text = reader.pages[0].extract_text()

    print("\nFILE:", file.name)
    print(text[:300])
    print("-" * 80)

FILE: 2608.20316v1_Pandora's AI Model Routing Box Efficient Allocation with Costly Value Estimation.pdf
2026-08-21
Pandora’s AI Model Routing Box: Efficient
Allocation with Costly Value Estimation
Adam Fisch∗, Shubhendu Trivedi, Fantine Huot, William W. Cohen, Michael Kaisers, Mirella Lapata, Kate
Larson, Jacob Eisenstein∗
Google DeepMind
Heterogeneous AI systems composed of multiple models, architect
--------------------------------------------------------------------------------

FILE: 2608.20318v1_AI4AI-Bench Benchmarking LLM Agents in Algorithmic Design for Recursive Self-Imp.pdf
AI4AI-Bench: Benchmarking LLM Agents in
Algorithmic Design for Recursive Self-Improvement
Yizhe Chi †, Wenyi Li, Deyao Hong, Xiaoqiu Wang, Mingju Gao, Kaisen Yang, Bingxiang He, Y oujie Zheng, Calvin Xiao,
Qinhuai Na ‡
Navers Lab, Einsia.AI T singhua University
†Project Lead ‡Corresponding Author
Ab
--------------------------------------------------------------------------------

FILE: 2608.20319v1_Inducing Task Models from Computer-Use Traces.pdf
Inducing Task Models from Computer-Use Traces
Yucheng Jiang1 Zora Zhiruo Wang2 Ruishi Chen1 Diyi Yang1
1Stanford University 2Carnegie Mellon University
{yuchengj,diyiy}@cs.stanford.edu
Abstract
Naturalistic computer-use traces, passively
recorded screenshots and mouse or keyboard
actions, are a valu
--------------------------------------------------------------------------------

FILE: 2608.20320v1_An Agentic Approach for Active Data Collection, Travel Behavior Modeling, and We.pdf
An Agentic Approach for Active Data Collection, Travel
Behavior Modeling, and Weather-Sensitive Demand
Prediction
Narges Ahmadi a,*, Yubo Jiao a, Jônatas Augusto Manzolli a, Jiangbo Yu a, Luis
Miranda-Morenoa
aDepartment of Civil Engineering, McGill University, Montreal, Quebec, Canada
Abstract
Trav
--------------------------------------------------------------------------------

FILE: 2608.20331v1_G-CARL Grounded Checklist-Aligned Reward Learning for Patient-Oriented Medical R.pdf
G-CARL: Grounded Checklist-Aligned Reward Learning for
Patient-Oriented Medical Report Interpretation
Shiao Xie1∗, Siyu Chen1∗, Jianwei Lv1, Bo Yuan1, Yujin Wang1†, Xiandong Li1†
1Baidu Inc., China
Abstract
Personalized interpretation of medical reports has emerged
as an increasingly important need
--------------------------------------------------------------------------------

In [13]:
print("duplicate filenames:", file_df["filename"].duplicated().sum())
print("duplicate titles:", papers_df["title"].duplicated().sum())

duplicate filenames: 0
duplicate titles: 0

In [14]:
metadata_rows = []

for file in files:
    reader = PdfReader(file)
    metadata = reader.metadata

    metadata_rows.append({
        "filename": file.name,
        "title": metadata.get("/Title"),
        "author": metadata.get("/Author"),
        "doi": metadata.get("/DOI"),
        "license": metadata.get("/License")
    })

metadata_df = pd.DataFrame(metadata_rows)
metadata_df

,filename,title,author,doi,license
0,2608.20316v1_Pandora's AI Model Routing Box Ef...,Pandora's AI Model Routing Box: Efficient Allo...,Adam Fisch; Shubhendu Trivedi; Fantine Huot; W...,https://doi.org/10.48550/arXiv.2608.20316,http://creativecommons.org/licenses/by/4.0/
1,2608.20318v1_AI4AI-Bench Benchmarking LLM Agen...,AI4AI-Bench: Benchmarking LLM Agents in Algori...,Yizhe Chi; Wenyi Li; Deyao Hong; Xiaoqiu Wang;...,https://doi.org/10.48550/arXiv.2608.20318,http://creativecommons.org/licenses/by/4.0/
2,2608.20319v1_Inducing Task Models from Compute...,Inducing Task Models from Computer-Use Traces,Yucheng Jiang; Zora Zhiruo Wang; Ruishi Chen; ...,https://doi.org/10.48550/arXiv.2608.20319,http://arxiv.org/licenses/nonexclusive-distrib...
3,2608.20320v1_An Agentic Approach for Active Da...,An Agentic Approach for Active Data Collection...,Narges Ahmadi; Yubo Jiao; Jônatas Augusto Manz...,https://doi.org/10.48550/arXiv.2608.20320,http://arxiv.org/licenses/nonexclusive-distrib...
4,2608.20331v1_G-CARL Grounded Checklist-Aligned...,G-CARL: Grounded Checklist-Aligned Reward Lear...,Shiao Xie; Siyu Chen; Jianwei Lv; Bo Yuan; Yuj...,https://doi.org/10.48550/arXiv.2608.20331,http://arxiv.org/licenses/nonexclusive-distrib...

## Data Quality Findings

- The dataset contains 5 unique arXiv research papers, all in PDF format.
- All 5 PDFs opened successfully and contained extractable text on every page.
- Titles and author information were available for all papers.
- DOI and license information were also available in the PDF metadata.
- No duplicate filenames or paper titles were found.
- No missing values were found in the fields collected during the assessment.
- The extracted text is readable overall, although some formatting artifacts are present, including missing spaces, merged words, and extra symbols around author names and affiliations.

### Usability for the RAG Pipeline

The following information should be useful for the RAG pipeline:
- Full paper text
- Paper titles
- Author information
- arXiv IDs from the filenames
- DOI and license information
- PDF page information that can be preserved later for citations and source tracking

The dataset looks usable for the RAG prototype. All 5 papers were readable, no duplicate filenames or titles were found, and the metadata needed for source tracking is available. Some formatting issues were found in the extracted text, including missing spaces, merged words, and extra symbols around author names and affiliations. These issues should be handled during the data cleaning and preprocessing stage before the text is split into chunks for retrieval.

# Part 2: Data Prep

Task #3 clean and process data

In [15]:
# extra imports , output dir

import re
import json
import unicodedata
from dataclasses import dataclass
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("ingestion_pipeline")

processed_dir = data_dir.parent / "data_processed"
processed_dir.mkdir(exist_ok=True)

print("Processed output directory:", processed_dir)

Processed output directory: /Users/janhhavibeley/Desktop/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed

In [16]:
# extract per page text

def extract_arxiv_id(filename: str) -> str:
    """Pull the arXiv ID (e.g. 2608.20316v1) off the front of the filename."""
    match = re.match(r"([\d]{4}\.[\d]{5}v\d+)", filename)
    return match.group(1) if match else filename


def extract_pdf_pages(file_path: Path) -> list[dict]:
    """Extract one record per page, with document-level metadata attached to every row."""
    reader = PdfReader(file_path)
    meta = reader.metadata or {}

    records = []
    for page_number, page in enumerate(reader.pages, start=1):
        raw_text = page.extract_text() or ""
        records.append({
            "arxiv_id": extract_arxiv_id(file_path.name),
            "filename": file_path.name,
            "title": meta.get("/Title"),
            "author": meta.get("/Author"),
            "doi": meta.get("/DOI"),
            "license": meta.get("/License"),
            "page_number": page_number,
            "num_pages": len(reader.pages),
            "raw_text": raw_text
        })
    return records


all_pages = []
for file in files:
    logger.info(f"Extracting {file.name}")
    all_pages.extend(extract_pdf_pages(file))

pages_df = pd.DataFrame(all_pages)
print(f"Extracted {len(pages_df)} pages from {pages_df['filename'].nunique()} papers")
pages_df.head()

2026-10-06 15:33:52,315 | INFO | Extracting 2608.20316v1_Pandora's AI Model Routing Box Efficient Allocation with Costly Value Estimation.pdf
2026-10-06 15:33:55,251 | INFO | Extracting 2608.20318v1_AI4AI-Bench Benchmarking LLM Agents in Algorithmic Design for Recursive Self-Imp.pdf
2026-10-06 15:33:58,389 | INFO | Extracting 2608.20319v1_Inducing Task Models from Computer-Use Traces.pdf
2026-10-06 15:34:00,092 | INFO | Extracting 2608.20320v1_An Agentic Approach for Active Data Collection, Travel Behavior Modeling, and We.pdf
2026-10-06 15:34:01,970 | INFO | Extracting 2608.20331v1_G-CARL Grounded Checklist-Aligned Reward Learning for Patient-Oriented Medical R.pdf

Extracted 104 pages from 5 papers

,arxiv_id,filename,title,author,doi,license,page_number,num_pages,raw_text
0,2608.20316v1,2608.20316v1_Pandora's AI Model Routing Box Ef...,Pandora's AI Model Routing Box: Efficient Allo...,Adam Fisch; Shubhendu Trivedi; Fantine Huot; W...,https://doi.org/10.48550/arXiv.2608.20316,http://creativecommons.org/licenses/by/4.0/,1,28,2026-08-21\nPandora’s AI Model Routing Box: Ef...
1,2608.20316v1,2608.20316v1_Pandora's AI Model Routing Box Ef...,Pandora's AI Model Routing Box: Efficient Allo...,Adam Fisch; Shubhendu Trivedi; Fantine Huot; W...,https://doi.org/10.48550/arXiv.2608.20316,http://creativecommons.org/licenses/by/4.0/,2,28,Pandora’s AI Model Routing Box: Efficient Allo...
2,2608.20316v1,2608.20316v1_Pandora's AI Model Routing Box Ef...,Pandora's AI Model Routing Box: Efficient Allo...,Adam Fisch; Shubhendu Trivedi; Fantine Huot; W...,https://doi.org/10.48550/arXiv.2608.20316,http://creativecommons.org/licenses/by/4.0/,3,28,Pandora’s AI Model Routing Box: Efficient Allo...
3,2608.20316v1,2608.20316v1_Pandora's AI Model Routing Box Ef...,Pandora's AI Model Routing Box: Efficient Allo...,Adam Fisch; Shubhendu Trivedi; Fantine Huot; W...,https://doi.org/10.48550/arXiv.2608.20316,http://creativecommons.org/licenses/by/4.0/,4,28,Pandora’s AI Model Routing Box: Efficient Allo...
4,2608.20316v1,2608.20316v1_Pandora's AI Model Routing Box Ef...,Pandora's AI Model Routing Box: Efficient Allo...,Adam Fisch; Shubhendu Trivedi; Fantine Huot; W...,https://doi.org/10.48550/arXiv.2608.20316,http://creativecommons.org/licenses/by/4.0/,5,28,Pandora’s AI Model Routing Box: Efficient Allo...

In [17]:
# clean text

def clean_text(text: str) -> str:
    """Clean raw PDF-extracted text based on artifacts identified in the Part 1 assessment."""
    if not text or not text.strip():
        return ""

    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"-\s*\n\s*", "", text)              # rejoin hyphenated line breaks
    text = re.sub(r"(\w)-\s+(\w)", r"\1-\2", text)      # rejoin hyphenated stray spacing
    text = re.sub(r"\s[\*†‡]\s", " ", text)             # strip isolated footnote markers
    text = re.sub(r"\n+", " ", text)                    # collapse newlines
    text = re.sub(r"[ \t]+", " ", text)                 # collapse repeated whitespace

    return text.strip()


pages_df["cleaned_text"] = pages_df["raw_text"].apply(clean_text)
pages_df["char_count"] = pages_df["cleaned_text"].str.len()
pages_df["word_count"] = pages_df["cleaned_text"].str.split().str.len()

print("BEFORE:\n", pages_df.loc[0, "raw_text"][:300])
print("\nAFTER:\n", pages_df.loc[0, "cleaned_text"][:300])

BEFORE:
 2026-08-21
Pandora’s AI Model Routing Box: Efficient
Allocation with Costly Value Estimation
Adam Fisch∗, Shubhendu Trivedi, Fantine Huot, William W. Cohen, Michael Kaisers, Mirella Lapata, Kate
Larson, Jacob Eisenstein∗
Google DeepMind
Heterogeneous AI systems composed of multiple models, architect

AFTER:
 2026-08-21 Pandora’s AI Model Routing Box: Efficient Allocation with Costly Value Estimation Adam Fisch∗, Shubhendu Trivedi, Fantine Huot, William W. Cohen, Michael Kaisers, Mirella Lapata, Kate Larson, Jacob Eisenstein∗ Google DeepMind Heterogeneous AI systems composed of multiple models, architect

In [18]:
# chunk text

CHUNK_SIZE_WORDS = 250
CHUNK_OVERLAP_WORDS = 40


def chunk_text(text: str, chunk_size: int = CHUNK_SIZE_WORDS, overlap: int = CHUNK_OVERLAP_WORDS) -> list[str]:
    """Split text into overlapping word-based chunks. Returns [] for empty text."""
    words = text.split()
    if not words:
        return []
    if len(words) <= chunk_size:
        return [text]

    chunks = []
    start = 0
    while start < len(words):
        end = start + chunk_size
        chunks.append(" ".join(words[start:end]))
        start += chunk_size - overlap
    return chunks


chunk_records = []
for _, row in pages_df.iterrows():
    page_chunks = chunk_text(row["cleaned_text"])
    for chunk_index, chunk in enumerate(page_chunks):
        chunk_records.append({
            "chunk_id": f"{row['arxiv_id']}_p{row['page_number']}_c{chunk_index}",
            "arxiv_id": row["arxiv_id"],
            "filename": row["filename"],
            "title": row["title"],
            "author": row["author"],
            "doi": row["doi"],
            "license": row["license"],
            "page_number": row["page_number"],
            "chunk_index": chunk_index,
            "text": chunk,
            "word_count": len(chunk.split())
        })

chunks_df = pd.DataFrame(chunk_records)
print(f"Produced {len(chunks_df)} chunks from {pages_df['filename'].nunique()} papers")
chunks_df[["chunk_id", "page_number", "word_count"]].head(10)

Produced 300 chunks from 5 papers

             chunk_id  page_number  word_count
0  2608.20316v1_p1_c0            1         250
1  2608.20316v1_p1_c1            1         250
2  2608.20316v1_p1_c2            1         124
3  2608.20316v1_p2_c0            2         250
4  2608.20316v1_p2_c1            2         250
5  2608.20316v1_p2_c2            2         204
6  2608.20316v1_p3_c0            3         250
7  2608.20316v1_p3_c1            3         250
8  2608.20316v1_p3_c2            3         244
9  2608.20316v1_p3_c3            3          34

In [19]:
# validate

assert not chunks_df.empty, "No chunks were produced"
assert chunks_df["chunk_id"].is_unique, "Duplicate chunk IDs found"
assert (chunks_df["word_count"] > 0).all(), "Empty chunks found"
assert chunks_df["title"].notna().all(), "Chunks missing title metadata"
assert chunks_df["arxiv_id"].notna().all(), "Chunks missing arxiv_id"
assert (chunks_df["word_count"] <= CHUNK_SIZE_WORDS + 5).all(), "Chunk exceeds target size unexpectedly"

print("All validation checks passed.")
print("\nChunk word-count distribution:")
print(chunks_df["word_count"].describe())

All validation checks passed.

Chunk word-count distribution:
count    300.000000
mean     201.453333
std       73.333716
min        2.000000
25%      149.500000
50%      250.000000
75%      250.000000
max      250.000000
Name: word_count, dtype: float64

In [20]:
#save 
#install pyarrow

%pip install pyarrow

jsonl_path = processed_dir / "chunks.jsonl"
parquet_path = processed_dir / "chunks.parquet"

with open(jsonl_path, "w") as f:
    for record in chunks_df.to_dict(orient="records"):
        f.write(json.dumps(record) + "\n")

chunks_df.to_parquet(parquet_path, index=False)

logger.info(f"Saved {len(chunks_df)} chunks to {jsonl_path}")
logger.info(f"Saved {len(chunks_df)} chunks to {parquet_path}")

Requirement already satisfied: pyarrow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (24.0.0)
Note: you may need to restart the kernel to use updated packages.

2026-10-06 15:34:05,770 | INFO | Saved 300 chunks to /Users/janhhavibeley/Desktop/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.jsonl
2026-10-06 15:34:05,771 | INFO | Saved 300 chunks to /Users/janhhavibeley/Desktop/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.parquet

In [21]:
# wrap as a repeatable pipeline 

@dataclass
class IngestionConfig:
    data_dir: Path
    output_dir: Path
    chunk_size_words: int = CHUNK_SIZE_WORDS
    chunk_overlap_words: int = CHUNK_OVERLAP_WORDS


class ArxivIngestionPipeline:
    def __init__(self, config: IngestionConfig):
        self.config = config
        self.pages_df = None
        self.chunks_df = None

    def extract(self):
        pdf_files = sorted([f for f in self.config.data_dir.iterdir() if f.suffix.lower() == ".pdf"])
        records = []
        for file in pdf_files:
            logger.info(f"Extracting {file.name}")
            records.extend(extract_pdf_pages(file))
        self.pages_df = pd.DataFrame(records)
        return self

    def clean(self):
        self.pages_df["cleaned_text"] = self.pages_df["raw_text"].apply(clean_text)
        return self

    def chunk(self):
        records = []
        for _, row in self.pages_df.iterrows():
            page_chunks = chunk_text(
                row["cleaned_text"],
                chunk_size=self.config.chunk_size_words,
                overlap=self.config.chunk_overlap_words
            )
            for chunk_index, chunk in enumerate(page_chunks):
                records.append({
                    "chunk_id": f"{row['arxiv_id']}_p{row['page_number']}_c{chunk_index}",
                    "arxiv_id": row["arxiv_id"],
                    "filename": row["filename"],
                    "title": row["title"],
                    "author": row["author"],
                    "doi": row["doi"],
                    "license": row["license"],
                    "page_number": row["page_number"],
                    "chunk_index": chunk_index,
                    "text": chunk,
                    "word_count": len(chunk.split())
                })
        self.chunks_df = pd.DataFrame(records)
        return self

    def validate(self):
        assert not self.chunks_df.empty, "No chunks produced"
        assert self.chunks_df["chunk_id"].is_unique, "Duplicate chunk IDs"
        assert (self.chunks_df["word_count"] > 0).all(), "Empty chunks found"
        assert self.chunks_df["title"].notna().all(), "Missing title metadata"
        return self

    def load(self):
        self.config.output_dir.mkdir(exist_ok=True)
        jsonl_path = self.config.output_dir / "chunks.jsonl"
        with open(jsonl_path, "w") as f:
            for record in self.chunks_df.to_dict(orient="records"):
                f.write(json.dumps(record) + "\n")
        self.chunks_df.to_parquet(self.config.output_dir / "chunks.parquet", index=False)
        logger.info(f"Saved {len(self.chunks_df)} chunks to {self.config.output_dir}")
        return self

    def run(self):
        return self.extract().clean().chunk().validate().load()


config = IngestionConfig(data_dir=data_dir, output_dir=processed_dir)
pipeline = ArxivIngestionPipeline(config)
pipeline.run()
print(f"Pipeline complete: {len(pipeline.chunks_df)} chunks ready for embedding")

2026-10-06 15:34:05,790 | INFO | Extracting 2608.20316v1_Pandora's AI Model Routing Box Efficient Allocation with Costly Value Estimation.pdf
2026-10-06 15:34:07,923 | INFO | Extracting 2608.20318v1_AI4AI-Bench Benchmarking LLM Agents in Algorithmic Design for Recursive Self-Imp.pdf
2026-10-06 15:34:09,796 | INFO | Extracting 2608.20319v1_Inducing Task Models from Computer-Use Traces.pdf
2026-10-06 15:34:11,404 | INFO | Extracting 2608.20320v1_An Agentic Approach for Active Data Collection, Travel Behavior Modeling, and We.pdf
2026-10-06 15:34:12,678 | INFO | Extracting 2608.20331v1_G-CARL Grounded Checklist-Aligned Reward Learning for Patient-Oriented Medical R.pdf
2026-10-06 15:34:13,735 | INFO | Saved 300 chunks to /Users/janhhavibeley/Desktop/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed

Pipeline complete: 300 chunks ready for embedding

## Summary

- Extracted per-page text and metadata for all 5 papers.
- Cleaned hyphenation breaks, stray footnote symbols, and irregular whitespace found during Part 1.
- Chunked text at the page level (250 words, 40-word overlap) so every chunk keeps an accurate page number for citations.
- Validated that every chunk has complete metadata, a unique ID, and non-empty text.
- Packaged the flow into `ArxivIngestionPipeline` for repeatable reruns.
- Output: `data_processed/chunks.jsonl` and `chunks.parquet`, ready for embedding.

# Part 3

RAG Model building

In [22]:
# install dependencies
# llamaindex is the core framework that wraps the other components (embeddings, vector stores, LLMs) together
# chromadb is a vector database for the embeddings

%pip install llama-index-core llama-index-embeddings-huggingface llama-index-vector-stores-chroma llama-index-llms-groq chromadb

import os
import chromadb

from llama_index.core import VectorStoreIndex, StorageContext, Settings
from llama_index.core.schema import TextNode
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.llms.groq import Groq

Requirement already satisfied: llama-index-core in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.14.25)
Requirement already satisfied: llama-index-embeddings-huggingface in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.8.0)
Requirement already satisfied: llama-index-vector-stores-chroma in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.6.0)
Requirement already satisfied: llama-index-llms-groq in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.6.1)
Requirement already satisfied: chromadb in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.5.9)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (3.14.3)
Requirement already satisfied: aiosqlite in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (0.22.1)
Requirement already satisfied: banks<3,>=2.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (2.5.1)
Requirement already satisfied: dataclasses-json in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (1.3.1)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (2026.2.0)
Requirement already satisfied: httpx in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (0.28.1)
Requirement already satisfied: llama-index-workflows<3,>=2.14.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (2.25.0)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /Users/janhhavibeley/Library/Python/3.11/lib/python/site-packages (from llama-index-core) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (3.6.1)
Requirement already satisfied: nltk>=3.9.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (3.10.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (2.4.6)
Requirement already satisfied: pillow>=9.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (12.0.0)
Requirement already satisfied: platformdirs in /Users/janhhavibeley/Library/Python/3.11/lib/python/site-packages (from llama-index-core) (4.9.1)
Requirement already satisfied: pydantic>=2.8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (2.13.4)
Requirement already satisfied: pyyaml>=6.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (2.32.5)
Requirement already satisfied: setuptools>=80.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (81.0.0)
Requirement already satisfied: sqlalchemy>=1.4.49 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core) (2.1.1)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (0.14.0)
Requirement already satisfied: tinytag>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (2.3.2)
Requirement already satisfied: tqdm<5,>=4.66.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (4.67.3)
Requirement already satisfied: typing-extensions>=4.5.0 in /Users/janhhavibeley/Library/Python/3.11/lib/python/site-packages (from llama-index-core) (4.15.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (0.9.0)
Requirement already satisfied: wrapt in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-core) (1.17.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.25.1)
Requirement already satisfied: griffe in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from banks<3,>=2.3.0->llama-index-core) (2.3.0)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from banks<3,>=2.3.0->llama-index-core) (3.1.6)
Requirement already satisfied: llama-index-instrumentation>=0.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-workflows<3,>=2.14.0->llama-index-core) (0.6.0)
Requirement already satisfied: idna>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yarl<2.0,>=1.17.0->aiohttp<4,>=3.8.6->llama-index-core) (3.11)
Requirement already satisfied: huggingface-hub>=0.19.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.4.1)
Requirement already satisfied: sentence-transformers>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-embeddings-huggingface) (6.1.0)
Requirement already satisfied: llama-index-llms-openai-like<0.9,>=0.8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-llms-groq) (0.8.0)
Requirement already satisfied: llama-index-llms-openai<0.8,>=0.7.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (0.7.10)
Requirement already satisfied: openai<3,>=1.108.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (2.53.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from openai<3,>=1.108.1->llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from openai<3,>=1.108.1->llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from openai<3,>=1.108.1->llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (0.16.0)
Requirement already satisfied: sniffio in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from openai<3,>=1.108.1->llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (1.3.1)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpx->llama-index-core) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpx->llama-index-core) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpcore==1.*->httpx->llama-index-core) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic>=2.8.0->llama-index-core) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic>=2.8.0->llama-index-core) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic>=2.8.0->llama-index-core) (0.4.2)
Requirement already satisfied: build>=1.0.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (2.15.0)
Requirement already satisfied: pybase64>=1.4.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (1.5.0)
Requirement already satisfied: uvicorn>=0.18.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.52.1)
Requirement already satisfied: onnxruntime>=1.14.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (1.30.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (1.45.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (1.45.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (1.45.0)
Requirement already satisfied: tokenizers>=0.13.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (0.23.1)
Requirement already satisfied: kubernetes>=28.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (36.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (5.3.0)
Requirement already satisfied: orjson>=3.9.12 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (3.12.0)
Requirement already satisfied: rich>=10.11.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (14.3.2)
Requirement already satisfied: jsonschema>=4.19.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from build>=1.0.3->chromadb) (25.0)
Requirement already satisfied: pyproject_hooks in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.24.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.2.0)
Requirement already satisfied: shellingham in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.5.4)
Requirement already satisfied: typer-slim in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.23.1)
WARNING: huggingface-hub 1.4.1 does not provide the extra 'inference'
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (2026.6.3)
Requirement already satisfied: six>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests-oauthlib in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (1.26.20)
Requirement already satisfied: durationpy>=0.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (0.11)
Requirement already satisfied: defusedxml in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nltk>=3.9.3->llama-index-core) (0.7.1)
Requirement already satisfied: click in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nltk>=3.9.3->llama-index-core) (8.3.1)
Requirement already satisfied: joblib in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nltk>=3.9.3->llama-index-core) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nltk>=3.9.3->llama-index-core) (2026.1.15)
Requirement already satisfied: flatbuffers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from onnxruntime>=1.14.1->chromadb) (6.33.5)
Requirement already satisfied: googleapis-common-protos~=1.57 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.4)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (0.66b0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.0)
Requirement already satisfied: opentelemetry-proto==1.45.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.66b0)
Requirement already satisfied: python-dotenv>=0.21.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests>=2.31.0->llama-index-core) (3.4.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/janhhavibeley/Library/Python/3.11/lib/python/site-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (5.1.0)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [23]:
# load chunks

chunks_df = pd.read_parquet(processed_dir / "chunks.parquet")
print(f"loaded {len(chunks_df)} chunks from {processed_dir / 'chunks.parquet'}")

loaded 300 chunks from /Users/janhhavibeley/Desktop/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.parquet

In [24]:
# convert raw chunks into llamaindex textnodes, i.e. units with text and metadata

nodes = []
for _, row in chunks_df.iterrows():
    node = TextNode(
        text=row["text"],
        metadata={
            "arxiv_id": row["arxiv_id"],
            "filename": row["filename"],
            "title": row["title"],
            "author": row["author"],
            "doi": row["doi"],
            "license": row["license"],
            "page_number": row["page_number"],
        }
    )
    nodes.append(node)

print(f"built {len(nodes)} nodes")

built 300 nodes

In [25]:
# config embedding model

Settings.embed_model = HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2")

2026-10-06 15:34:39,656 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:39,675 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/modules.json "HTTP/1.1 200 OK"
2026-10-06 15:34:39,714 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:39,726 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-10-06 15:34:39,731 | INFO | Loading SentenceTransformer model from sentence-transformers/all-MiniLM-L6-v2.
2026-10-06 15:34:39,765 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-10-06 15:34:39,768 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-10-06 15:34:39,781 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-10-06 15:34:39,817 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:39,831 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/README.md "HTTP/1.1 200 OK"
2026-10-06 15:34:39,870 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:39,883 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/modules.json "HTTP/1.1 200 OK"
2026-10-06 15:34:39,920 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:39,936 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-10-06 15:34:39,980 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-10-06 15:34:40,016 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:40,064 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 128.91it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-10-06 15:34:42,415 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-10-06 15:34:42,465 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-06 15:34:42,499 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-06 15:34:42,530 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-06 15:34:42,570 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:42,583 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/tokenizer_config.json "HTTP/1.1 200 OK"
2026-10-06 15:34:42,626 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:42,639 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config.json "HTTP/1.1 200 OK"
2026-10-06 15:34:42,676 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:42,688 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config.json "HTTP/1.1 200 OK"
2026-10-06 15:34:42,723 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:42,737 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/tokenizer_config.json "HTTP/1.1 200 OK"
2026-10-06 15:34:42,785 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-06 15:34:42,823 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-10-06 15:34:43,062 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-06 15:34:43,074 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-10-06 15:34:43,116 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/2_Normalize/config.json "HTTP/1.1 404 Not Found"
2026-10-06 15:34:43,160 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2 "HTTP/1.1 200 OK"

# Part 4 - Baseline RAG Evaluation

In [26]:
# Part 4: Baseline RAG Evaluation

import chromadb
import pandas as pd

from llama_index.core import VectorStoreIndex, StorageContext
from llama_index.vector_stores.chroma import ChromaVectorStore

In [27]:
# Create benchmark questions

benchmark_questions = [
    {
        "id": "Q1",
        "question": "What problem does Pandora's AI Model Routing Box aim to solve?",
        "expected_arxiv_id": "2608.20316v1"
    },
    {
        "id": "Q2",
        "question": "How does Pandora's AI Model Routing Box improve the efficiency of AI model selection?",
        "expected_arxiv_id": "2608.20316v1"
    },
    {
        "id": "Q3",
        "question": "What is AI4AI-Bench designed to evaluate?",
        "expected_arxiv_id": "2608.20318v1"
    },
    {
        "id": "Q4",
        "question": "How does AI4AI-Bench assess the performance of LLM agents in algorithmic design?",
        "expected_arxiv_id": "2608.20318v1"
    },
    {
        "id": "Q5",
        "question": "What information is used to induce task models from computer-use traces?",
        "expected_arxiv_id": "2608.20319v1"
    },
    {
        "id": "Q6",
        "question": "What is the purpose of the agentic approach for active data collection and travel behaviour modelling?",
        "expected_arxiv_id": "2608.20320v1"
    },
    {
        "id": "Q7",
        "question": "What problem does grounded checklist-aligned reward learning address in patient-oriented medical research?",
        "expected_arxiv_id": "2608.20331v1"
    },
    {
        "id": "Q8",
        "question": "How is reward learning used to improve patient-oriented medical outcomes?",
        "expected_arxiv_id": "2608.20331v1"
    }
]

benchmark_df = pd.DataFrame(benchmark_questions)

benchmark_df

   id                                           question expected_arxiv_id
0  Q1  What problem does Pandora's AI Model Routing B...      2608.20316v1
1  Q2  How does Pandora's AI Model Routing Box improv...      2608.20316v1
2  Q3          What is AI4AI-Bench designed to evaluate?      2608.20318v1
3  Q4  How does AI4AI-Bench assess the performance of...      2608.20318v1
4  Q5  What information is used to induce task models...      2608.20319v1
5  Q6  What is the purpose of the agentic approach fo...      2608.20320v1
6  Q7  What problem does grounded checklist-aligned r...      2608.20331v1
7  Q8  How is reward learning used to improve patient...      2608.20331v1

In [28]:
# Create Chroma vector store

chroma_client = chromadb.PersistentClient(
    path=str(processed_dir / "chroma_db")
)

chroma_collection = chroma_client.get_or_create_collection(
    name="baseline_rag"
)

vector_store = ChromaVectorStore(
    chroma_collection=chroma_collection
)

storage_context = StorageContext.from_defaults(
    vector_store=vector_store
)

In [29]:
# Create the baseline vector index

index = VectorStoreIndex(
    nodes,
    storage_context=storage_context,
    show_progress=True
)

retriever = index.as_retriever(
    similarity_top_k=5
)

Generating embeddings: 100%|██████████| 300/300 [00:45<00:00,  6.63it/s]

In [30]:
# Test baseline retrieval

test_question = benchmark_questions[0]["question"]

results = retriever.retrieve(test_question)

for rank, result in enumerate(results, start=1):
    print(f"Rank {rank}")
    print(f"arXiv ID: {result.node.metadata.get('arxiv_id')}")
    print(f"Title: {result.node.metadata.get('title')}")
    print(f"Page: {result.node.metadata.get('page_number')}")
    print()

Rank 1
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 2
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 3
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 4
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 18

Rank 5
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 18

In [31]:
# Evaluate baseline retrieval

retrieval_results = []

for item in benchmark_questions:

    results = retriever.retrieve(item["question"])

    retrieved_ids = [
        result.node.metadata.get("arxiv_id")
        for result in results
    ]

    expected_id = item["expected_arxiv_id"]

    retrieval_results.append({
        "id": item["id"],
        "question": item["question"],
        "expected_arxiv_id": expected_id,
        "retrieved_ids": retrieved_ids,
        "hit_at_1": expected_id in retrieved_ids[:1],
        "hit_at_3": expected_id in retrieved_ids[:3],
        "hit_at_5": expected_id in retrieved_ids[:5]
    })

evaluation_df = pd.DataFrame(retrieval_results)

evaluation_df

,id,question,expected_arxiv_id,retrieved_ids,hit_at_1,hit_at_3,hit_at_5
0,Q1,What problem does Pandora's AI Model Routing B...,2608.20316v1,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260...",True,True,True
1,Q2,How does Pandora's AI Model Routing Box improv...,2608.20316v1,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260...",True,True,True
2,Q3,What is AI4AI-Bench designed to evaluate?,2608.20318v1,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260...",True,True,True
3,Q4,How does AI4AI-Bench assess the performance of...,2608.20318v1,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260...",True,True,True
4,Q5,What information is used to induce task models...,2608.20319v1,"[2608.20319v1, 2608.20319v1, 2608.20319v1, 260...",True,True,True
5,Q6,What is the purpose of the agentic approach fo...,2608.20320v1,"[2608.20320v1, 2608.20320v1, 2608.20320v1, 260...",True,True,True
6,Q7,What problem does grounded checklist-aligned r...,2608.20331v1,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260...",True,True,True
7,Q8,How is reward learning used to improve patient...,2608.20331v1,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260...",True,True,True

In [32]:
# Calculate retrieval metrics

hit_at_1 = evaluation_df["hit_at_1"].mean()
hit_at_3 = evaluation_df["hit_at_3"].mean()
hit_at_5 = evaluation_df["hit_at_5"].mean()

print("Baseline Retrieval Performance")
print("-" * 40)
print(f"Hit@1: {hit_at_1:.2%}")
print(f"Hit@3: {hit_at_3:.2%}")
print(f"Hit@5: {hit_at_5:.2%}")

Baseline Retrieval Performance
----------------------------------------
Hit@1: 100.00%
Hit@3: 100.00%
Hit@5: 100.00%

In [33]:
# Save baseline retrieval results

evaluation_df.to_csv(
    processed_dir / "baseline_retrieval_evaluation.csv",
    index=False
)

Okay, so far 100% Hit for 1,3, and 5 indicates that it was able to retrieve a chunk from the expected paper. However, we do not know if the RAG system generates correct answers.

Will be using Groq generation and evalluate the answers below.

In [34]:
# Set up Groq

import os
from dotenv import load_dotenv

from llama_index.core import Settings
from llama_index.llms.groq import Groq

load_dotenv()

groq_api_key = os.getenv("GROQ_API_KEY")

llm = Groq(
    model="openai/gpt-oss-20b",
    api_key=groq_api_key
)

Settings.llm = llm

In [35]:
# Test Groq with one question

question = benchmark_questions[0]["question"]

results = retriever.retrieve(question)

context = "\n\n".join([
    f"""
Source:
Title: {result.node.metadata.get('title')}
arXiv ID: {result.node.metadata.get('arxiv_id')}
Page: {result.node.metadata.get('page_number')}

Text:
{result.node.text}
"""
    for result in results
])

prompt = f"""
You are a research intelligence assistant.

Answer the question using only the research context provided below.

Question:
{question}

Research context:
{context}

Instructions:
- Give a concise and factual answer.
- Do not use information outside the provided context.
- If the context does not contain enough information, say so.
- At the end of your answer, provide the source arXiv ID.
"""

response = llm.complete(prompt)

print(response.text)

2026-10-06 15:35:47,022 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Pandora’s AI Model Routing Box is designed to address the problem of efficiently allocating AI models to incoming tasks while taking into account the cost of estimating each model’s value. It seeks to minimize regret and inspection cost by routing queries to the most appropriate model under a budget‑constrained value‑estimation setting.

Source: arXiv 2608.20316v1

In [36]:
# Generate a RAG answer

def generate_rag_answer(question):

    results = retriever.retrieve(question)

    context = "\n\n".join([
        f"""
Source:
Title: {result.node.metadata.get('title')}
arXiv ID: {result.node.metadata.get('arxiv_id')}
Page: {result.node.metadata.get('page_number')}

Text:
{result.node.text}
"""
        for result in results
    ])

    prompt = f"""
You are a research intelligence assistant.

Answer the question using only the research context provided below.

Question:
{question}

Research context:
{context}

Instructions:
- Give a concise and factual answer.
- Do not use information outside the provided context.
- If the context does not contain enough information, say so.
- At the end of your answer, provide the source arXiv ID.
"""

    response = llm.complete(prompt)

    return response.text, results

In [37]:
# Generate answers for all benchmark questions

rag_results = []

for item in benchmark_questions:

    answer, results = generate_rag_answer(
        item["question"]
    )

    retrieved_ids = [
        result.node.metadata.get("arxiv_id")
        for result in results
    ]

    rag_results.append({
        "id": item["id"],
        "question": item["question"],
        "expected_arxiv_id": item["expected_arxiv_id"],
        "answer": answer,
        "retrieved_ids": retrieved_ids
    })

rag_results_df = pd.DataFrame(rag_results)

rag_results_df

2026-10-06 15:35:48,711 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:50,150 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:50,305 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:35:50,308 | INFO | Retrying request to /chat/completions in 2.000000 seconds
2026-10-06 15:35:53,302 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:53,517 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:35:53,518 | INFO | Retrying request to /chat/completions in 17.000000 seconds
2026-10-06 15:36:11,728 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:13,087 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:13,089 | INFO | Retrying request to /chat/completions in 13.000000 seconds
2026-10-06 15:36:26,723 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:27,866 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:27,905 | INFO | Retrying request to /chat/completions in 9.000000 seconds
2026-10-06 15:36:37,366 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:37,377 | INFO | Retrying request to /chat/completions in 4.000000 seconds
2026-10-06 15:36:42,088 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:43,608 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:43,613 | INFO | Retrying request to /chat/completions in 28.000000 seconds
2026-10-06 15:37:11,919 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:37:11,925 | INFO | Retrying request to /chat/completions in 3.000000 seconds
2026-10-06 15:37:15,789 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:37:16,606 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:37:16,611 | INFO | Retrying request to /chat/completions in 25.000000 seconds
2026-10-06 15:37:42,769 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

,id,question,expected_arxiv_id,answer,retrieved_ids
0,Q1,What problem does Pandora's AI Model Routing B...,2608.20316v1,Pandora’s AI Model Routing Box tackles the cha...,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260..."
1,Q2,How does Pandora's AI Model Routing Box improv...,2608.20316v1,Pandora’s AI Model Routing Box improves effici...,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260..."
2,Q3,What is AI4AI-Bench designed to evaluate?,2608.20318v1,AI4AI‑Bench is a benchmark that tests whether ...,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260..."
3,Q4,How does AI4AI-Bench assess the performance of...,2608.20318v1,AI4AI‑Bench evaluates an LLM agent by letting ...,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260..."
4,Q5,What information is used to induce task models...,2608.20319v1,Task models are induced from the low‑level eve...,"[2608.20319v1, 2608.20319v1, 2608.20319v1, 260..."
5,Q6,What is the purpose of the agentic approach fo...,2608.20320v1,The agentic approach is designed to unify the ...,"[2608.20320v1, 2608.20320v1, 2608.20320v1, 260..."
6,Q7,What problem does grounded checklist-aligned r...,2608.20331v1,Grounded checklist‑aligned reward learning (G‑...,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260..."
7,Q8,How is reward learning used to improve patient...,2608.20331v1,Reward learning in G‑CARL improves patient‑ori...,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260..."

In [38]:
# Review generated answers

for _, row in rag_results_df.iterrows():

    print(f"--- {row['id']} ---")
    print(f"Question: {row['question']}")
    print()
    print(f"Answer: {row['answer']}")
    print()
    print(f"Expected source: {row['expected_arxiv_id']}")
    print("-" * 60)

--- Q1 ---
Question: What problem does Pandora's AI Model Routing Box aim to solve?

Answer: Pandora’s AI Model Routing Box tackles the challenge of **efficiently allocating tasks to AI models when estimating each model’s value is expensive**—i.e., it seeks to optimize routing decisions while accounting for the cost of value estimation.

Source: arXiv 2608.20316v1

Expected source: 2608.20316v1
------------------------------------------------------------
--- Q2 ---
Question: How does Pandora's AI Model Routing Box improve the efficiency of AI model selection?

Answer: Pandora’s AI Model Routing Box improves efficiency by routing queries to the most valuable models using a cost‑aware value‑estimation framework.  The system employs value estimators (Section C.1) and carefully designed prompts (Section C.2) to predict each model’s expected benefit, allowing it to limit the number of inspections (see Supplemental Results D.1) and the monetary cost of value‑function evaluations (Supplemental Results D.3).  This targeted allocation reduces overall regret plus inspection cost, as shown in Table 4 on RAG routing, where the Box achieves the lowest combined metric among compared methods.

Source: arXiv 2608.20316v1.

Expected source: 2608.20316v1
------------------------------------------------------------
--- Q3 ---
Question: What is AI4AI-Bench designed to evaluate?

Answer: AI4AI‑Bench is a benchmark that tests whether a large‑language‑model agent can write code that improves the training algorithm of a repository’s own model.  The agent’s submission is evaluated by running the modified code under the same conditions as the original, and a fixed evaluator computes a metric (e.g., accuracy, solve‑rate, loss).  The benchmark measures whether the agent’s code yields a better metric than the baseline, thus assessing the agent’s ability to perform recursive self‑improvement in algorithm design.

Source: arXiv 2608.20318v1

Expected source: 2608.20318v1
------------------------------------------------------------
--- Q4 ---
Question: How does AI4AI-Bench assess the performance of LLM agents in algorithmic design?

Answer: AI4AI‑Bench evaluates an LLM agent by letting it modify the training algorithm of a frozen research repository and then measuring the quality of the resulting model with a **fixed, pre‑defined evaluator**.

1. **Baseline** – The original repository’s code is run once to produce a baseline model \(C\).
2. **Agent submission** – The agent’s code produces a modified training algorithm \(C'\).
3. **Evaluation** – Both \(C\) and \(C'\) are trained under identical conditions (same hardware, budget, and evaluator).
4. **Metric** – A fixed evaluator \(m\) computes a scalar score \(s(C)=m(a(C))\) and \(s(C')=m(a(C'))\).
5. **Improvement test** – The submission is considered better if
   \[
   s(C') > s(C) \quad \text{for upward‑directed metrics (↑)} \quad\text{or}\quad
   s(C') < s(C) \quad \text{for downward‑directed metrics (↓)} .
   \]
6. **Dense scoring** – Rather than a binary win/lose, the benchmark reports the actual metric value, providing a dense score that reflects the magnitude of improvement.

Thus, AI4AI‑Bench assesses performance by comparing the evaluator‑derived metric of the agent‑generated model to that of the baseline, using a dense, direction‑aware score.

**Source:** arXiv:2608.20318v1.

Expected source: 2608.20318v1
------------------------------------------------------------
--- Q5 ---
Question: What information is used to induce task models from computer-use traces?

Answer: Task models are induced from the low‑level events that are passively recorded during computer use: screenshots of the screen and the corresponding mouse or keyboard actions.

Source: arXiv 2608.20319v1

Expected source: 2608.20319v1
------------------------------------------------------------
--- Q6 ---
Question: What is the purpose of the agentic approach for active data collection and travel behaviour modelling?

Answer: The agentic approach is designed to unify the traditionally separate stages of travel‑behavior research into a single, transparent, and modular workflow. By linking a conversational data‑collection agent, a structured data‑processing agent, and a behavioral‑prediction agent, it enables an AI‑assisted survey to capture context‑dependent travel behavior and to feed that data directly into predictive models (e.g., LLMs, DCMs, ML benchmarks). The goal is to streamline the process from survey administration to behavioral prediction while allowing systematic evaluation of how different information types and AI configurations affect mode‑choice accuracy.

Source: arXiv 2608.20320v1

Expected source: 2608.20320v1
------------------------------------------------------------
--- Q7 ---
Question: What problem does grounded checklist-aligned reward learning address in patient-oriented medical research?

Answer: Grounded checklist‑aligned reward learning (G‑CARL) tackles the problem of producing **clinically accurate, evidence‑grounded interpretations of medical reports that also respect patient‑specific context and clinical checklists**. In patient‑oriented medical research, existing methods (e.g., simple fine‑tuning or “LLM‑as‑a‑Judge”) often misdiagnose abnormalities, ignore relevant patient history, or fail to answer the user’s primary question. G‑CARL aligns the model’s outputs with a checklist of clinical criteria and evidence‑based rewards, thereby improving diagnostic accuracy, contextual integration, and recommendation quality.

**Source:** arXiv:2608.20331v1

Expected source: 2608.20331v1
------------------------------------------------------------
--- Q8 ---
Question: How is reward learning used to improve patient-oriented medical outcomes?

Answer: Reward learning in G‑CARL improves patient‑oriented medical outcomes by providing fine‑grained, evidence‑grounded supervision for language models that interpret medical reports. The framework decomposes rewards into two types:

1. **Retrieval‑grounded claim reward** – each atomic medical claim in a generated response is verified against the uploaded report and a multi‑source medical datastore. This gives localized feedback on factual accuracy and discourages unsupported elaboration, ensuring that the information patients receive is verifiable and clinically reliable.

2. **Checklist‑guided reward** – for context‑dependent goals such as demand satisfaction and expression quality, G‑CARL generates instance‑specific weighted checklists (refined by clinicians). The reward emphasizes the checklist items most relevant to the current report and user question, providing transparent supervision that the response addresses the patient’s concerns appropriately.

By aligning rewards with verifiability and patient‑specific needs, G‑CARL consistently outperforms supervised and other reinforcement‑learning baselines, with gains confirmed by clinician preference and user comprehension studies. This leads to more accurate, relevant, and patient‑friendly medical interpretations, thereby improving patient‑oriented outcomes.

**Source:** arXiv ID 2608.20331v1.

Expected source: 2608.20331v1
------------------------------------------------------------

In [40]:
# Create answer evaluation table

answer_evaluation_df = rag_results_df[
    [
        "id",
        "question",
        "answer",
        "expected_arxiv_id"
    ]
].copy()

# Manual evaluation
# 0 = poor, 1 = partial, 2 = strong

answer_evaluation_df["answer_relevance"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df["faithfulness"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df["citation_accuracy"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df

,id,question,answer,expected_arxiv_id,answer_relevance,faithfulness,citation_accuracy
0,Q1,What problem does Pandora's AI Model Routing B...,Pandora’s AI Model Routing Box tackles the cha...,2608.20316v1,2,2,2
1,Q2,How does Pandora's AI Model Routing Box improv...,Pandora’s AI Model Routing Box improves effici...,2608.20316v1,2,2,2
2,Q3,What is AI4AI-Bench designed to evaluate?,AI4AI‑Bench is a benchmark that tests whether ...,2608.20318v1,2,2,2
3,Q4,How does AI4AI-Bench assess the performance of...,AI4AI‑Bench evaluates an LLM agent by letting ...,2608.20318v1,2,2,2
4,Q5,What information is used to induce task models...,Task models are induced from the low‑level eve...,2608.20319v1,2,2,2
5,Q6,What is the purpose of the agentic approach fo...,The agentic approach is designed to unify the ...,2608.20320v1,2,2,2
6,Q7,What problem does grounded checklist-aligned r...,Grounded checklist‑aligned reward learning (G‑...,2608.20331v1,2,2,2
7,Q8,How is reward learning used to improve patient...,Reward learning in G‑CARL improves patient‑ori...,2608.20331v1,2,2,2

In [41]:
# Calculate generation metrics

answer_relevance = (
    answer_evaluation_df["answer_relevance"].mean() / 2
)

faithfulness = (
    answer_evaluation_df["faithfulness"].mean() / 2
)

citation_accuracy = (
    answer_evaluation_df["citation_accuracy"].mean() / 2
)

print("Baseline RAG Generation Performance")
print("-" * 40)
print(f"Answer Relevance: {answer_relevance:.2%}")
print(f"Faithfulness: {faithfulness:.2%}")
print(f"Citation Accuracy: {citation_accuracy:.2%}")

Baseline RAG Generation Performance
----------------------------------------
Answer Relevance: 100.00%
Faithfulness: 100.00%
Citation Accuracy: 100.00%

In [42]:
# Final baseline RAG results

final_results = pd.DataFrame({
    "Metric": [
        "Hit@1",
        "Hit@3",
        "Hit@5",
        "Answer Relevance",
        "Faithfulness",
        "Citation Accuracy"
    ],
    "Score": [
        hit_at_1,
        hit_at_3,
        hit_at_5,
        answer_relevance,
        faithfulness,
        citation_accuracy
    ]
})

final_results["Score"] = final_results["Score"].map(
    lambda x: f"{x:.2%}"
)

final_results

              Metric    Score
0              Hit@1  100.00%
1              Hit@3  100.00%
2              Hit@5  100.00%
3   Answer Relevance  100.00%
4       Faithfulness  100.00%
5  Citation Accuracy  100.00%

In [43]:
# Save generated RAG answers

rag_results_df.to_csv(
    processed_dir / "baseline_rag_answers.csv",
    index=False
)

print("Saved: baseline_rag_answers.csv")

Saved: baseline_rag_answers.csv

In [44]:
# Save manual answer evaluation

answer_evaluation_df.to_csv(
    processed_dir / "baseline_answer_evaluation.csv",
    index=False
)

print("Saved: baseline_answer_evaluation.csv")

Saved: baseline_answer_evaluation.csv

In [45]:
# Save final baseline RAG results

final_results.to_csv(
    processed_dir / "baseline_rag_results.csv",
    index=False
)

print("Saved: baseline_rag_results.csv")

Saved: baseline_rag_results.csv

## Baseline RAG Evaluation Summary

The baseline RAG pipeline was evaluated using an eight-question benchmark covering the five research papers in the dataset. Retrieval performance was measured using Hit@1, Hit@3, and Hit@5, while generated responses were manually evaluated for answer relevance, faithfulness to the retrieved context, and citation accuracy.

The baseline achieved 100% Hit@1, Hit@3, and Hit@5 on the benchmark. The generated responses also achieved 100% on answer relevance, faithfulness, and citation accuracy based on the manual evaluation.

These results indicate that the baseline pipeline successfully retrieved the expected source paper and generated relevant, context-supported answers for the benchmark questions. However, the benchmark contains only eight questions, so these results should be interpreted as baseline performance on the current evaluation set rather than evidence of general RAG performance.

## Evaluation Methodology

### Retrieval Evaluation

Retrieval performance was evaluated using three metrics:

- **Hit@1:** whether the expected source paper was ranked first.
- **Hit@3:** whether the expected source paper appeared within the top three retrieved results.
- **Hit@5:** whether the expected source paper appeared within the top five retrieved results.

### Generation Evaluation

Generated answers were manually evaluated using a 0–2 scale:

- **Answer Relevance:** whether the response directly answers the benchmark question.
- **Faithfulness:** whether the response is supported by the retrieved research context.
- **Citation Accuracy:** whether the cited arXiv source corresponds to the expected source paper.

A score of 2 represents a strong result, 1 represents a partial result, and 0 represents an incorrect or unsupported result.